[[redirects]]
  from = "/api/*"
  to = "https://ai-supabase-agent-b3l4e7s4eq-uc.a.run.app/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[build]
  command = "npm run build"
  publish = ".next"
